# Association Rules

#### In this section, we will learn about how to use assocition rules in python and how to filter data based on different metrics of association rules.


Following libraries are used for association rules:
- pandas
- numpy
- matplotlib
- mlxtend

In [2]:
# Import necessary modules

import numpy as np
import pandas as pd
import csv
from matplotlib import pyplot as plt

# Import Apriori module and TransactionEncoder module and association module from mlxtend

from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import association_rules as arule

### Read data from repair.csv

We use repair.csv file as a data set for finding frequent item sets. Apriori algorithm is used for finding frequent itemsets.

In [9]:
# Read file 'repair.csv' and change the data format for Apriori algorithm

data_set = []

with open("repair.csv") as csvFile:
    reader = csv.reader(csvFile)
    for row in reader:
        data_set.append(row)
        
data_set

[['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Inform User',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Inform User',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Inform User',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Inform User',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Inform User',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Inform User',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Inform User',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Inform User',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Inform User',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Inform User'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Inform User',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Inform User',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Inform User',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Simple)',
  'Inform User',
  'Repair (Simple)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',
  'Repair (Simple)',
  'Test Repair',
  'Inform User',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Restart Repair',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair',
  'Archive Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Complex)',
  'Inform User',
  'Repair (Complex)',
  'Test Repair',
  'Test Repair'],
 ['Register',
  'Analyze Defect',
  'Analyze Defect',
  'Repair (Simple)',

In [7]:
# learn to use TransactionEncoder module to convert an array to DataFrame for Apriori algorithm in mlxtend

te = TransactionEncoder()
te_ary = te.fit(data_set).transform(data_set)
data = pd.DataFrame(te_ary, columns = te.columns_)
data.tail(5)
# learn to use Apriori algorithm from mlxtend

frequent_itemsets = apriori(data, min_support = 0.4, use_colnames = True)

In [8]:
data

,Analyze Defect,Archive Repair,Inform User,Register,Repair (Complex),Repair (Simple),Restart Repair,Test Repair
0,True,True,True,True,True,False,False,True
1,True,True,True,True,False,True,True,True
2,True,True,True,True,True,False,False,True
3,True,True,True,True,False,True,False,True
4,True,False,True,True,True,False,False,True
...,...,...,...,...,...,...,...,...
1099,True,True,True,True,True,False,False,True
1100,True,True,True,True,True,False,False,True
1101,True,True,True,True,True,False,False,True
1102,True,True,True,True,True,False,False,True
1103,True,True,True,True,False,True,True,True

### Filtering data based on metrics of Association rules
In python you can filter frequent itemsets based on different metrics such as support, confidence and lift.

In [ ]:
# learn to use association rule algorithm from mlxtend and filter data based on one metric.

rules_association =arule(frequent_itemsets, metric = 'lift', min_threshold = 0.8)
rules_association

#### Question:Change the metric to lift and support. Inevestigate the effect of that on the table.

### Finding qualified frequent itemsets using association rules
You can use association rules for finding qualified itemsets for different datasets.

#### Question:  Find frequent item sets with minimum support of 0.4. Store them in frequent_itemsets variable.

In [10]:
#Answer
frequent_itemsets = apriori(data, min_support = 0.4, use_colnames = True)
frequent_itemsets

     support                                           itemsets
0   1.000000                                   (Analyze Defect)
1   0.905797                                   (Archive Repair)
2   0.998188                                      (Inform User)
3   1.000000                                         (Register)
4   0.596920                                 (Repair (Complex))
..       ...                                                ...
74  0.550725  (Analyze Defect, Repair (Complex), Register, T...
75  0.595109  (Analyze Defect, Inform User, Repair (Complex)...
76  0.438406  (Analyze Defect, Inform User, Register, Test R...
77  0.550725  (Inform User, Repair (Complex), Register, Test...
78  0.550725  (Analyze Defect, Inform User, Repair (Complex)...

[79 rows x 2 columns]

### Filtering itemsets based on length and metrics of assosciation rules
In this section, you will learn how to filter frequent item sets based on length of them.

In [ ]:
# Add another column named 'length' in 'frequent_itemsets' which indicates the number of items in each frequent itemset.

frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

# Filter out the frequent itemsets which have a length longer than 2 and a support bigger than 0.3. 

# Store these found itemsets in variable 'frequent_itemsets_filtered'.

frequent_itemsets_filtered = frequent_itemsets.loc[(frequent_itemsets['length'] > 2) & (frequent_itemsets['support'] > 0.3)]   
frequent_itemsets_filtered

### Demonstrating selective metrics of association rules in one table
 In this section, you will learn how to show selective metrics of association rules in one table.

In [ ]:
# Mine association rules from the discovered frequent itemsets stored in variable 'frequent_itemsets', set minimum confidence to 0.5.

# Store the discovered rules in variable 'rules_association'.

rules_association =arule(frequent_itemsets, metric = 'confidence', min_threshold = 0.5)

# Filter out the rules with lift larger than 1 and support larger than 0.4, store the discovered rules in variable 'filtered_rules'.

filtered_rules = rules_association.loc[(rules_association['lift'] > 1) & (rules_association['support'] > 0.4)]     

# Show the columns 'antecedents', 'consequents', 'support', 'confidence' and 'lift' of variable 'filtered_rules' 

filtered_rules[['support', 'confidence', 'lift']]